### ISSUE TITLE
User is randomly kicked off out of auth session

### ISSUE THREAD

**Issue by pavgra** [OHDSI/ArachneNodeAPI#321]
Details to be completed by @acumarav

**Comment by acumarav** [comment]
Caused by the token signature validation failure

**Comment by acumarav** [comment]
io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:342) ~[jjwt-0.6.0.jar:0.6.0]
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:458) ~[jjwt-0.6.0.jar:0.6.0]
	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:518) ~[jjwt-0.6.0.jar:0.6.0]
	at com.odysseusinc.arachne.portal.security.TokenUtils.getClaimsFromToken(TokenUtils.java:155) [classes/:na]
	at com.odysseusinc.arachne.portal.security.TokenUtils.getUsernameFromToken(TokenUtils.java:100) [classes/:na]
	at com.odysseusinc.arachne.portal.security.AuthenticationTokenFilter.doFilter(AuthenticationTokenFilter.java:78) [classes/:na]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.12.RELEASE.jar:4.2.12.RELEASE]
	at com.odysseusinc.arachne.portal.security.AuthenticationSystemTokenFilter.doFilter(AuthenticationSystemTokenFilter.java:72) [classes/:na]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.12.RELEASE.jar:4.2.12.RELEASE]
	at com.odysseusinc.arachne.portal.config.WebSecurityConfig$HostFilter.doFilterInternal(WebSecurityConfig.java:242) [classes/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.23.RELEASE.jar:4.3.23.RELEASE]
